# Site settings
title: build blog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A blog to document the building of my personal site
baseurl: "/buildblog" # the subpath of your site, e.g. /blog/
url: "http://danlucas.github.com" # the base hostname & protocol for your site
twitter_username: danlucas
github_username:  danlucas

# Build settings
markdown: kramdown

#rake task settings
post:
  template: _templates/post.txt
  extension: md
page:
  template: _templates/page.txt
  extension: md
editor: atom
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/username.github.com/
